In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
data = pd.read_csv('train.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [5]:
data.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8  ...      pixel774      pixel775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [6]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [7]:
data = np.array(data)

In [8]:
data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
m, n = data.shape
print(m,n)

42000 785


In [10]:
np.random.shuffle(data)

In [11]:
data = pd.read_csv("train.csv").to_numpy()
np.random.shuffle(data)

x = data[:, 1:].T / 255.0
y = data[:, 0]

x_train = x[:, 1000:]
y_train = y[1000:]

x_dev = x[:, :1000]
y_dev = y[:1000]

In [12]:
#data_dev = data[0:1000].T

In [13]:
#y_dev = data_dev[0]
#x_dev = data_dev[1:n]

In [14]:
#data_train  = data[1000:m].T
#y_train = data_train[0]
#x_train = data_train[1:n]

In [15]:
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

{0: 4025, 1: 4577, 2: 4093, 3: 4247, 4: 3978, 5: 3707, 6: 4027, 7: 4296, 8: 3969, 9: 4081}


In [16]:
def init_params():
    w1 = np.random.randn(10, x_train.shape[0]) * 0.01
    b1 = np.zeros((10, 1))
    w2 = np.random.randn(10, 10) * 0.01
    b2 = np.zeros((10, 1))
    return w1, b1, w2, b2

In [17]:
def Relu(z):
    return np.maximum(0,z)

In [18]:
#def softmax(z):
#    A = np.exp(z) / np.sum(np.exp(z))
#    return A
def softmax(z):
    z -= np.max(z, axis=0, keepdims=True)  # stability trick
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=0, keepdims=True)

In [19]:
def forward_prop(w1,b1,w2,b2,x):
    z1 = w1.dot(x) + b1
    a1 = Relu(z1)
    z2 = w2.dot(a1) + b2
    a2 = softmax(z2)
    return z1,a1,z2,a2

In [20]:
def one_hot(y):
    one_hot_y = np.zeros((y.size, y.max()+1))
    one_hot_y[(np.arange(y.size), y)] = 1
    one_hot_y = one_hot_y.T
    return one_hot_y

In [21]:
def deriv_relu(z):
    return z>0

In [22]:
def back_prop(z1,a1,z2,a2,w2,x,y):
    m = y.size
    one_hot_y = one_hot(y)
    dz2 = a2 - one_hot_y
    dw2 = 1/m * dz2.dot(a1.T)
    db2 = 1/m * np.sum(dz2, axis=1, keepdims=True)
    dz1 = w2.T.dot(dz2) * deriv_relu(z1)
    dw1 = 1/m * dz1.dot(x.T)
    db1 = 1/m * np.sum(dz1, axis=1, keepdims=True) 
    return dw1,db1,dw2,db2

In [23]:
def update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, alpha):
    w1 = w1 - alpha * dw1
    b1 = b1 - alpha * db1
    w2 = w2 - alpha * dw2
    b2 = b2 - alpha * db2
    return w1,b1,w2,b2

In [24]:
def get_predictions(A2):
    return np.argmax(A2,0)

In [25]:
def get_accuracy(predictions, y):
    print(predictions, y)
    return np.sum(predictions == y)/y.size

In [26]:
def gradient_descent(x, y, iterations, alpha):
    w1,b1,w2,b2 = init_params()
    for i in range(iterations):
        z1,a1,z2,a2 = forward_prop(w1,b1,w2,b2,x)

        dw1,db1,dw2,db2 = back_prop(z1,a1,z2,a2,w2,x,y)

        w1,b1,w2,b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)

        if (i % 10 == 0 and i>0):
            print("iteration: ", i) 
            print("Accuracy: ", get_accuracy(get_predictions(a2), y))
    return w1,b1,w2,b2

In [29]:
w1,b1,w2,b2 = gradient_descent(x_train, y_train, 500, 0.05)

iteration:  10
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.11756097560975609
iteration:  20
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.11163414634146342
iteration:  30
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.11163414634146342
iteration:  40
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.11163414634146342
iteration:  50
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.11173170731707317
iteration:  60
[1 1 1 ... 1 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.12224390243902439
iteration:  70
[1 7 1 ... 7 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.1778780487804878
iteration:  80
[1 7 1 ... 7 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.23307317073170733
iteration:  90
[1 9 1 ... 7 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.25365853658536586
iteration:  100
[1 9 1 ... 9 1 1] [5 7 3 ... 9 5 3]
Accuracy:  0.24734146341463414
iteration:  110
[9 9 1 ... 9 9 1] [5 7 3 ... 9 5 3]
Accuracy:  0.2430731707317073
iteration:  120
[9 9 1 ... 9 9 1] [5 7 3 ... 9 5 3]
Accuracy:  0.2572926829268293
iteration:  130


In [28]:
# Forward pass on dev (test) set
_, _, _, a2_dev = forward_prop(w1, b1, w2, b2, x_dev)

# Accuracy on dev set
print("Test Accuracy:", get_accuracy(get_predictions(a2_dev), y_dev))


[0 1 2 7 3 3 8 9 0 6 2 9 4 2 3 4 6 9 8 4 4 9 4 7 9 6 0 9 6 0 9 9 5 9 1 0 5
 9 9 2 7 6 5 6 6 9 6 9 2 6 3 3 3 3 7 2 7 6 5 9 0 2 5 8 6 0 1 8 7 1 1 2 8 0
 9 3 3 9 3 3 0 2 1 9 4 1 3 8 2 0 2 3 7 5 3 5 5 9 1 2 7 9 8 4 3 0 5 0 9 1 4
 5 6 9 6 8 4 0 5 9 6 2 4 6 7 6 6 2 0 7 7 3 9 7 4 1 3 4 4 3 5 5 3 6 6 4 7 2
 9 5 1 6 7 2 4 2 8 3 8 5 5 8 4 2 7 9 7 4 5 9 6 6 1 6 6 3 8 7 3 0 1 9 2 6 2
 3 7 9 4 3 9 9 6 8 9 5 1 6 0 3 7 8 5 9 7 6 2 4 1 8 4 8 2 9 9 4 7 0 1 6 3 2
 6 5 0 9 9 7 6 0 0 4 2 6 3 6 4 5 8 3 8 1 6 3 8 0 1 4 2 6 2 1 0 7 6 4 2 4 6
 3 7 6 6 4 0 0 1 0 0 1 9 6 3 8 4 8 8 3 4 7 4 2 4 5 5 6 6 3 3 6 1 5 9 3 0 0
 3 4 4 1 8 0 0 6 4 6 7 7 8 0 6 3 8 8 0 8 4 0 5 0 9 3 6 0 7 6 1 6 2 6 5 0 8
 5 2 7 5 0 9 5 9 6 0 8 5 9 6 9 5 1 9 8 0 0 3 8 7 2 8 0 8 7 4 4 2 7 1 6 8 8
 7 5 6 7 2 7 7 7 1 4 9 7 9 8 3 0 6 4 4 4 1 6 0 3 7 7 5 7 0 9 0 5 2 7 8 1 3
 1 7 8 7 0 8 1 0 5 1 1 3 1 2 5 4 6 1 1 1 1 0 3 3 1 0 9 8 9 8 2 7 9 5 4 2 2
 6 3 4 9 0 4 4 0 9 5 9 0 9 1 9 6 7 0 9 1 4 9 7 7 6 8 8 1 9 4 5 4 9 8 7 4 7
 9 8 8 4 8 9 5 1 3 4 1 0 